APP-5223: Implement API for tax information update
paysera/kotlin-lib-mokejimai-sdk pull request #31
Opened 2023-03-17 10:41 UTC by AndriiSerheniuk

2023-03-17 10:44 UTC, AndriiSerheniuk commented
manually parsing response as when no tins to update we getting 204 response No content

2023-03-21 05:20 UTC, gilbertparreno commented on src/main/kotlin/com/paysera/lib/mokejimai/clients/MokejimaiApiClient.kt
> +    suspend fun taxInformationMessages(userId: String): TaxInformationMessages {
Why do we need this extra gson instance?

2023-03-21 08:10 UTC, AndriiSerheniuk commented on src/main/kotlin/com/paysera/lib/mokejimai/clients/MokejimaiApiClient.kt
> +    suspend fun taxInformationMessages(userId: String): TaxInformationMessages {
if any tin to update BE returns 200 with tins list which is good but in case when no tin to update BE returns 204 No content and here is the problem. Retrofit cannot return anything because we expect object response not null. This is temporarily solution until BE resolve this [ticket](https://jira.paysera.net/browse/SUPPORT-71211)

2023-03-21 08:30 UTC, s-k-georgiev commented on src/main/kotlin/com/paysera/lib/mokejimai/entities/TaxInformationMessages.kt
> +)
Can we move those as separate classes?

2023-03-21 16:41 UTC, AndriiSerheniuk commented on src/main/kotlin/com/paysera/lib/mokejimai/entities/TaxInformationMessages.kt
> +)
I updated to follow the structure like [ManualTransferConfiguration](https://github.com/paysera/kotlin-lib-mokejimai-sdk/blob/master/src/main/kotlin/com/paysera/lib/mokejimai/entities/ManualTransferConfiguration.kt) and [LogData](https://github.com/paysera/kotlin-lib-mokejimai-sdk/blob/master/src/main/kotlin/com/paysera/lib/mokejimai/entities/LogData.kt)

2023-03-24 04:07 UTC, gilbertparreno commented on src/main/kotlin/com/paysera/lib/mokejimai/clients/MokejimaiApiClient.kt
> +    suspend fun taxInformationMessages(userId: String): TaxInformationMessages {
let's wait for that ticket to be fixed first before merging.

2023-03-30 09:24 UTC, gilbertparreno approved these changes

2023-03-30 14:28 UTC, s-k-georgiev commented on src/main/kotlin/com/paysera/lib/mokejimai/entities/TaxInformationMessages.kt
> +        val expiresIn: Int?,
Should this be of type `Date?`

2023-03-31 03:59 UTC, gilbertparreno requested changes

2023-03-31 03:59 UTC, gilbertparreno commented on src/main/kotlin/com/paysera/lib/mokejimai/entities/TaxInformationMessages.kt
> +        val expiresIn: Int?,
add @SerializeName("expires_in_days") to avoid confusion

2023-03-31 07:58 UTC, AndriiSerheniuk commented on src/main/kotlin/com/paysera/lib/mokejimai/entities/TaxInformationMessages.kt
> +        val expiresIn: Int?,
expiresIn renamed to expiresInDays

2023-04-03 11:03 UTC, gilbertparreno approved these changes

2023-04-03 13:34 UTC, merged